### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by hadim** [jchaney/owncloud#35]
I setup a docker-compose.yml file which works pretty well.

```yaml
owncloud-db:
  container_name: owncloud-db
  image: ${image_mariadb}
  volumes:
    - ${docker_owncloud_permanent_storage}/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${docker_owncloud_mariadb_root_password}
    - MYSQL_USER=owncloud
    - MYSQL_DATABASE=owncloud
    - MYSQL_PASSWORD=${docker_owncloud_mariadb_user_password}

owncloud-server:
  container_name: owncloud-server
  # image: ${image_owncloud}
  build: owncloud
  links:
    - owncloud-db:mysql
  ports:
    - "${docker_owncloud_http_port}:80"
    - "${docker_owncloud_https_port}:443"
  volumes:
    - ${docker_owncloud_permanent_storage}/data:/var/www/owncloud/data
    - ${docker_owncloud_permanent_storage}/additional_apps:/var/www/owncloud/apps_persistent
    - ${docker_owncloud_permanent_storage}/config:/owncloud
    - ${docker_owncloud_ssl_cert}:/owncloud.cert:ro
    - ${docker_owncloud_ssl_key}:/owncloud.key:ro
  environment:
    - OWNCLOUD_IN_ROOTPATH=${docker_owncloud_in_root_path}
    - OWNCLOUD_SERVERNAME=${docker_owncloud_servername}
    - SSL_CERT="/owncloud.cert"
    - SSL_KEY="/owncloud.key"
```

I use these variables : 

```sh
export docker_owncloud_http_port="80"
export docker_owncloud_https_port="443"
export docker_owncloud_in_root_path="1"
export docker_owncloud_permanent_storage="/home/hadim/owncloud_data"
export docker_owncloud_ssl_cert="./certs/cloud.cert"
export docker_owncloud_ssl_key="./certs/cloud.key"
export docker_owncloud_servername="arwen.hadim.fr"

export docker_owncloud_mariadb_root_password=$(pwgen --secure 40 1)
export docker_owncloud_mariadb_user_password=$(pwgen --secure 40 1)

export image_owncloud="jchaney/owncloud"
export image_mariadb="mysql"  # mariadb raises weird errors I don't understand...
```

And I also needed to slighty modify your repo : 

```diff
diff --git a/configs/owncloud_config.php b/configs/owncloud_config.php
index c0a18b2..6d33202 100644
--- a/configs/owncloud_config.php
+++ b/configs/owncloud_config.php
@@ -19,4 +19,11 @@ $CONFIG = array (
             'writable' => true,
         ),
     ),
+
+    "dbtype"        => "mysql",
+    "dbname"        => "conf_dbname",
+    "dbuser"        => "conf_dbuser",
+    "dbpassword"    => "conf_dbpassword",
+    "dbhost"        => "conf_dbhost",
+    "dbtableprefix" => "oc_",
 );
diff --git a/misc/bootstrap.sh b/misc/bootstrap.sh
index e8a8f33..f79dceb 100755
--- a/misc/bootstrap.sh
+++ b/misc/bootstrap.sh
@@ -7,6 +7,25 @@ touch /var/log/cron/owncloud.log
 test -e /owncloud/config.php || cp /root/owncloud_config.php /owncloud/config.php
 test -e /owncloud/3party_apps.conf || cp /root/3party_apps.conf /owncloud/
 
+# Check wether a mysql database is linked
+if [ -z "$MYSQL_PORT_3306_TCP_ADDR" ]
+then
+    # Erase database configuration of owncloud if no database are linked
+    sed -i 's/dbtype/d' /owncloud/config.php
+    sed -i 's/dbname/d' /owncloud/config.php
+    sed -i 's/dbuser/d' /owncloud/config.php
+    sed -i 's/dbpassword/d' /owncloud/config.php
+    sed -i 's/dbhost/d' /owncloud/config.php
+    sed -i 's/dbtableprefix/d' /owncloud/config.php
+else
+    # Set the configuration to the linked mysql database
+    sed -i "s/conf_dbname/$MYSQL_ENV_MYSQL_DATABASE/g" /owncloud/config.php
+    sed -i "s/conf_dbuser/$MYSQL_ENV_MYSQL_USER/g" /owncloud/config.php
+    sed -i "s/conf_dbpassword/$MYSQL_ENV_MYSQL_PASSWORD/g" /owncloud/config.php
+    sed -i "s/conf_dbhost/$MYSQL_PORT_3306_TCP_ADDR:$MYSQL_PORT_3306_TCP_PORT/g" /owncloud/config.p
+
+fi
+
 if [ -z "$SSL_CERT" ]
 then
     echo "Copying nginx.conf without SSL support …"
```

Unfortunately automatic database configuration does not work and I still need to execute the following command to get the credentials and then manually enter them in the owncloud wizard:

```sh
$ docker exec -ti owncloud-server cat /owncloud/config.php
<?php
$CONFIG = array (
  'installed' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/owncloud/apps_persistent',
      'url' => '/apps_persistent',
      'writable' => true,
    ),
  ),
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbpassword' => '78ryLjuqkG8Rx7kyNhAVNmVfo22Cqh8wPoQSrsBK',
  'dbhost' => '172.17.0.2:3306',
  'dbtableprefix' => 'oc_',
  'instanceid' => 'ocb8cq8uf1f7',
);
```

Thansk anyway for your work on this image !
